# Generated by Django 5.2.3 on 2025-07-10 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID отдела')),
                ('department_name', models.CharField(max_length=100, unique=True, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.IntegerField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID опроса')),
                ('poll_name', models.CharField(verbose_name='Название опроса')),
                ('poll_description', models.CharField(verbose_name='Описание опроса')),
                ('poll_duration', models.DurationField(blank=True)),
                ('is_unexpected', models.BooleanField(verbose_name='Является ли внеплановым')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('service_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Табельный номер')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('is_curator', models.BooleanField(verbose_name='Является ли куратором')),
                ('is_admin', models.BooleanField(verbose_name='Является ли администратором')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
                ('hire_date', models.DateField(verbose_name='Дата приёма на работу')),
                ('telegram_registration_date', models.DateField(auto_now_add=True, verbose_name='Дата первого обращения к боту')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.department')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.IntegerField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID вопроса')),
                ('question_name', models.CharField(verbose_name='Название вопроса')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.IntegerField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='ID ответа')),
                ('answer_name', models.CharField(verbose_name='Содержимое ответа')),
                ('service_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.employee')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
