# Generated by Django 5.2.3 on 2025-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID ответа'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID опроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID вопроса'),
        ),
    ]
