# Generated by Django 5.2.3 on 2025-07-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_answer_answer_id_alter_poll_poll_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='Answer',
        ),
        migrations.AlterModelTable(
            name='department',
            table='Department',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AlterModelTable(
            name='poll',
            table='Poll',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
