# Generated by Django 5.2.3 on 2025-07-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_rename_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='question',
            name='poll',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
