# Generated by Django 5.2.3 on 2025-07-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'db_table': 'Filial',
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название опроса')),
                ('description', models.CharField(blank=True, null=True, verbose_name='Описание опроса')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Время, через которое запускается опрос')),
                ('submission_date', models.DurationField(blank=True, null=True, verbose_name='Дата создания')),
                ('is_unexpected', models.BooleanField(default=False, verbose_name='Является ли внеплановым')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
                'db_table': 'Poll',
            },
        ),
        migrations.CreateModel(
            name='Struct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'Struct',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tab', models.CharField(blank=True, max_length=200, null=True, verbose_name='Табельный номер')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('post', models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('login', models.CharField(blank=True, max_length=200, null=True, verbose_name='Логин')),
                ('is_del', models.BooleanField(default=False, verbose_name='Уволен')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_can_manage_global_groups', models.BooleanField(default=False, verbose_name='Может управлять глобальными группами')),
                ('is_can_view_all_forms', models.BooleanField(default=False, verbose_name='Может просматривать все формы')),
                ('is_curator', models.BooleanField(default=False, verbose_name='Является ли куратором')),
                ('telegram_id', models.IntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приёма на работу')),
                ('telegram_registration_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата первого обращения к боту')),
                ('curator_login', models.CharField(blank=True, max_length=200, null=True, verbose_name='Логин куратора')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='core.filial', verbose_name='Филиал')),
                ('struct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='core.struct', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название вопроса')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.poll')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'Question',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Содержимое ответа')),
                ('submission_date', models.DurationField(blank=True, null=True, verbose_name='Дата создания')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'db_table': 'Answer',
            },
        ),
        migrations.CreateModel(
            name='Special_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Название вопроса')),
                ('answer', models.CharField(blank=True, null=True, verbose_name='Ответ на вопрос')),
                ('employee_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='core.employee', verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Специальный вопрос',
                'verbose_name_plural': 'Специальные вопросы',
                'db_table': 'Special_Question',
            },
        ),
    ]
