# Generated by Django 5.2.3 on 2025-07-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_question',
            name='submission_date',
            field=models.DurationField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
