# Generated by Django 5.2.3 on 2025-07-18 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_special_question_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special_question',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
